### ISSUE TITLE
errors during setup

### ISSUE THREAD

**Issue by kid1carus** [syns/repo.me#7]
I get the following errors when I run updaterepo.sh and im unsure how to fix them.
<img width="583" alt="Screen Shot 2021-02-08 at 5 06 46 PM" src="https://user-images.githubusercontent.com/45052773/107287808-7642dd00-6a30-11eb-8013-298e14a6f388.png">

**Comment by debouncedgit** [comment]
~~the first error `unable to read /etc/apt/apt.conf.d/` is normal, ignore it.~~ Fixed as of latest commit.
delete the sample deb.
